# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[toolchain]
channel = "stable" # Needs to be in "stable" otherwise won't compile with new mqtt client.
components = ["clippy", "llvm-tools-preview", "rustfmt"]
